import z from "zod";

export const EnumBackgroundAction = z.enum([
	"GET_FILTERED_SESSIONS_BY_ACTIVE_TAB",
	"SAVE_CURRENT_TAB_STORAGE_TO_EXTENSION_STORAGE",
	"UPDATE_SESSION_BY_ID",
	"DELETE_SESSION_BY_ID",
	"CREATE_NEW_SESSION",
	"REFRESH_CURRENT_TAB",
	"SWITCH_SESSION_BY_ID",
	"GET_ACTIVE_SESSION",
]);
